name: mitchell enterprises
favicon: null
layout_spectrum: 0.34023477230221033
typography_spectrum: 0.13512
title: Activities of Mitchell Enterprises
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1275c9'
    - '#dbe0e6'
    - '#432b17'
    - '#fa454a'
    - '#9e735e'
  brandStrength: 0.5
  lightness: 0.49086973536759615
  saturation: 0.5804552256595343
  rhythmicContrast: 0.596221667015925
purpose: []
